name: tfsec
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  
jobs:
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.0

  
        

  slackNotification:
    name: Slack Notification Demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Slack Notification Demo
        uses: bryannice/gitactions-slack-notification@2.0.0
        env:
          SLACK_INCOMING_WEBHOOK: ${{ secrets.SLACK_INCOMING_WEBHOOK }}
          SLACK_MESSAGE: 'Demo''ing the Slack Notification'
          SLACK_TITLE: 'Slack Notification Demo'        

